config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'flights#index'

  resources :flights
  resources :bookings
  resources :passengers
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'

  validates :code, presence: true, uniqueness: true
  validates :city, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings

  validates :departure_time, presence: true
  validates :flight_duration, presence: true

  def departure_date_formatted
    departure_time.strftime('%B %d, %Y')
  end

  def departure_time_formatted
    departure_time.strftime('%l:%M %P')
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :bookings

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @num_of_passengers = params[:num_of_passengers]
    @booking.passengers.build
  end

  def create
    @flight = Flight.find(booking_params[:flight_id])
    @booking = @flight.bookings.build(booking_params)

    if @booking.save
      PassengerMailer.with(booking: @booking).confirmation_email.deliver_later

      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,
                                    passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @departure_airport = Airport.where(id: query_params[:departure_airport_id])
    @arrival_airport = Airport.where(id: query_params[:arrival_airport_id])
    @departure_time = query_params[:departure_time]
    @num_of_passengers = query_params[:passengers]

    unless @departure_time.blank?
      @time = DateTime.parse(@departure_time)
      @start_time = DateTime.new(@time.year, @time.month, @time.day, 6, 0)
      @end_time = DateTime.new(@time.year, @time.month, @time.day, 11, 59)
    end

    @flights = Flight.where(
      departure_airport_id: Airport.where(id: @departure_airport),
      arrival_airport_id: Airport.where(id: @arrival_airport),
      departure_time: (@start_time..@end_time)
    ).order(:departure_time)
  end

  private

  def flight_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :date)
  end

  def query_params
    params.permit(:departure_airport_id, :arrival_airport_id, :departure_time,
                  :passengers, :flight_id, :commit, :authenticity_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Booking Information</h1>
<% if @booking.errors.any? %>
  <h2><%= pluralize(@booking.errors.count, 'error') %> prevented this booking from being created:</h2>
  <ul>
    <% @bookings.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<h4>
  <%= "#{@flight.departure_airport.city}
        (#{@flight.departure_airport.code}) \u2002 \u2192 \u2002
        #{@flight.arrival_airport.city}
        (#{@flight.arrival_airport.code})" %>
</h4>

<div>
  <%= "Departure: #{@flight.departure_time_formatted}" %>
</div>
<div>
  <%= "Duration: #{@flight.flight_duration.to_i} minutes" %>
</div>
<div>
  <%= "Flight Number: #{@flight.id}" %>
</div>

<%= form_with model: @booking, html: {id: "main_form", "data-controller": "passenger"} do |form| %>
  <%= form.hidden_field :number_of_passengers, data: { "passenger-numberOfPassengers-value": @num_of_passengers} %>

  <% (1..@num_of_passengers.to_i).each do |passenger_number| %>

    <div data-passenger-target="passengerBox">
      <h4><%= "Passenger Information" %></h4>
      <div>
        <%= form.fields_for :passengers do |sub_form| %>
          <%= form.hidden_field :flight_id, value: @flight.id %>
          <div>
            <%= sub_form.label :name, "Passenger name:" %>
            <%= sub_form.text_field :name, data: { "passenger-target": "name" } %>
          </div>

          <div>
            <%= sub_form.label :email, "Passenger email:" %>
            <%= sub_form.email_field :email, data: { "passenger-target": "email" } %>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

  <div class="buttons">
    <button data-action="passenger#add" type="button">Add Passenger</button>
    <button data-action="passenger#remove" type="button">Remove Passenger</button>
  </div>

  <%= form.submit 'Book Flight' %>

  <%# <div data-controller="passenger"> %>
    <template data-passenger-target="template">

      <div data-passenger-target="passengerBox">
        <h4><%= "Passenger Information" %></h4>
        <div>
          <%= form.fields_for :passengers do |sub_form| %>
            <%= form.hidden_field :flight_id, value: @flight.id %>
            <div>
              <%= sub_form.label :name, "Passenger name:", data: { "passenger-target": "nameLabel" } %>
            <%= sub_form.text_field :name, data: { "passenger-target": "name" } %>
            </div>

            <div>
              <%= sub_form.label :email, "Passenger email:", data: { "passenger-target": "emailLabel" } %>
            <%= sub_form.email_field :email, data: { "passenger-target": "email" } %>
            </div>
          <% end %>
        </div>
      </div>

    </template>
  <%# </div> %>

<% end %>

app/views/bookings/show.html.erb
<h1>Your flight has been booked!</h1>

<h2>Flight Information</h2>
<h4>
  <%= "#{@booking.flight.departure_airport.city}
          (#{@booking.flight.departure_airport.code}) \u2002 \u2192 \u2002
          #{@booking.flight.arrival_airport.city}
          (#{@booking.flight.arrival_airport.code})" %>
</h4>
<div>
  <%= "Departure: #{@booking.flight.departure_time_formatted}" %>
</div>
<div>
  <%= "Duration: #{@booking.flight.flight_duration.to_i} minutes" %>
</div>
<div>
  <%= "Flight Number: #{@booking.flight.id}" %>
</div>

<% @booking.passengers.each_with_index do |passenger, passenger_number| %>
  <% if @booking.passengers.count > 1 %>
    <h3><%= "Passenger #{passenger_number + 1} Information" %></h3>
  <% else %>
    <h3><%= "Passenger Information" %></h3>
  <% end %>

  <div>
    <p><strong>Name:</strong> <%= passenger.name.titleize %></p>
    <p><strong>Email:</strong> <%= passenger.email %></p>
  </div><br>
<% end %>

app/views/flights/_results.html.erb
<% unless @departure_airport.blank? && @arrival_airport.blank? && @departure_time.blank? %>
  <h2>Search Results</h2>

  <% if @flights.any? %>
    <%= form_with(model: @flight, url: new_booking_path, method: 'get') do |form| %>
      <%= form.hidden_field :num_of_passengers, value: @num_of_passengers %>

      <h4>
        <%= "#{pluralize(@flights.count, 'flight')} available
        for #{@flights.first.departure_date_formatted}" %>
      </h4>

      <% @flights.each do |flight| %>
        <div>
          <%= form.radio_button :flight_id, flight.id %>
          <%= form.label :flight_id, "#{flight.departure_airport.city}
                (#{flight.departure_airport.code}) \u2002 \u2192 \u2002
                #{flight.arrival_airport.city}
                (#{flight.arrival_airport.code})", :value => flight.id %> &#8194; | &#8194;
          <%= "Departure: #{flight.departure_time_formatted}" %> &#8194; | &#8194;
          <%= "Duration: #{flight.flight_duration.to_i} minutes" %>
        </div>
      <% end %>

      <%= form.submit 'Book' %>
    <% end %>
  <% else %>
    <h4>No flights found, please try again.</h4>
  <% end %>
<% end %>

app/views/flights/_search.html.erb
<%= form_with(model: @flight, url: flights_path, method: :get) do |form| %>
  <% @days = Flight.all.pluck(:departure_time).map { |day| day.strftime('%B %d, %Y') }.uniq %>
  <h4>Departure</h4>
  <%= select_tag 'departure_airport_id',
                  options_from_collection_for_select(@airports, 'id', 'city'),
                  include_blank: 'From' %>

  <h4>Arrival</h4>
  <%= select_tag 'arrival_airport_id',
                  options_from_collection_for_select(@airports, 'id', 'city'),
                  include_blank: 'To' %>

  <h4>Date</h4>
  <%= select_tag 'departure_time', options_for_select(@days),
                  include_blank: 'Departing', style: 'min-width: 144px' %>

  <h4>Passengers</h4>
  <%= select_tag :passengers, options_for_select(1..4), style: 'min-width: 40px' %>

  <%= form.submit 'Search' %>
<% end %>

app/views/flights/index.html.erb
<h1>Book a One-way Flight</h1>

<%= render 'search' %>
<%= render 'results' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>